apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: crud-lab
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: crud-lab
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          value: "carlos"
        - name: POSTGRES_PASSWORD
          value: "lab123"
        - name: POSTGRES_DB
          value: "observability_db"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432