apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: shop-lab
spec:
  type: NodePort
  ports:
    - name: "http"
      port: 3000
      targetPort: 3000
      nodePort: 30500 # Definido para bater com o health check
  selector:
    io.kompose.service: backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: shop-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      labels:
        io.kompose.service: backend
    spec:
      imagePullSecrets:
        - name: regcred # <--- A "chave" para o GHCR
      containers:
        - env:
            - name: DATABASE_URL
              value: postgres://user:password@db:5432/shop_db
            # Adicione as vars de Tracing para o novo namespace
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://jaeger-svc.observability:4318" 
          image: ghcr.io/carlosaralmeida/shop-api:v1
          name: shop-api
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"