[k8s_master]
k8s-master-01 ansible_host=172.22.0.29 ansible_user=ubuntu

[k8s_workers]
k8s-worker-01 ansible_host=172.22.0.30 ansible_user=ubuntu
k8s-worker-02 ansible_host=172.22.0.31 ansible_user=ubuntu

[k8s_cluster:children]
k8s_master
k8s_workers