- name: Deploy do Loki
  hosts: k8s_master
  become: true
  tasks:
    - name: Deploy Loki (Apenas o Servidor)
      kubernetes.core.helm:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        name: loki
        chart_ref: grafana/loki
        release_namespace: observability
        values:
          deploymentMode: SingleBinary
          
          # Desativação de componentes desnecessários para o lab
          chunksCache: { enabled: false }
          resultsCache: { enabled: false }
          memcached: { enabled: false }
          lokiCanary: { enabled: false }
          test: { enabled: false }
          gateway: { enabled: false }

          loki:
            auth_enabled: false
            commonConfig:
              replication_factor: 1
            storage:
              type: filesystem
              bucketNames:
                chunks: chunks
                tags: tags
                admin: admin
            schemaConfig:
              configs:
                - from: "2024-01-01"
                  store: tsdb
                  object_store: filesystem
                  schema: v13
                  index:
                    prefix: index_
                    period: 24h

          # --- AQUI ESTÁ O DETALHE QUE FALTAVA ---
          singleBinary:
            replicas: 1
            persistence:
              enabled: true
              size: 5Gi
              storageClass: local-path
            # No modo SingleBinary, o service deve ser habilitado aqui:
            service:
              type: NodePort
              nodePort: 31100

          # Garante que as réplicas dos outros modos fiquem em zero
          read: { replicas: 0 }
          write: { replicas: 0 }
          backend: { replicas: 0 }