---
- name: Deploy da infraestrutura do Banco de Dados
  hosts: k8s_master
  become: true
  tasks:
    - name: Garantir que o Namespace shop-lab existe
      kubernetes.core.k8s:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        name: shop-lab
        kind: Namespace
        state: present

    - name: Aplicar manifesto do Banco (ConfigMap, Service e Deployment)
      kubernetes.core.k8s:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        state: present
        # O lookup lê o arquivo no Runner e envia para o Master
        definition: "{{ lookup('file', '../kubernetes/web-db.yml') | from_yaml_all | list }}"
        namespace: shop-lab