- name: Deploy do Backend da aplicação Web
  hosts: k8s_master
  become: true
  tasks:
  - name: Garantir que o Namespace existe
    kubernetes.core.k8s:
      name: shop-lab
      kind: Namespace
      state: present
  - name: Aplicar manifesto do Backend
    kubernetes.core.k8s:
      kubeconfig: /etc/rancher/k3s/k3s.yaml
      state: present
      # O Pulo do Gato: 'lookup' lê o arquivo no GitHub Runner
      # e o 'from_yaml_all' garante que o K8s entenda os 3 recursos (ConfigMap, Deploy, Svc)
      definition: "{{ lookup('file', '../kubernetes/web-backend.yml') | from_yaml_all | list }}"
      namespace: shop-lab