---
- name: Setup Observability Stack (Helm + Prometheus + Grafana)
  hosts: k8s_master
  become: true
  tasks:
    - name: Baixar script de instalação do Helm (via curl para evitar bug de SSL do Python)
      shell: |
        curl -fsSL -o /tmp/get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 /tmp/get_helm.sh
      args:
        creates: /tmp/get_helm.sh

    - name: Executar instalação do Helm
      shell: /tmp/get_helm.sh
      args:
        creates: /usr/local/bin/helm

    - name: Adicionar repositórios Helm (Prometheus e Grafana)
      kubernetes.core.helm_repository:
        name: "{{ item.name }}"
        repo_url: "{{ item.url }}"
      loop:
        - { name: 'prometheus-community', url: 'https://prometheus-community.github.io/helm-charts' }
        - { name: 'grafana', url: 'https://grafana.github.io/helm-charts' }
      
    - name: Atualizar repositórios Helm
      shell: helm repo update

    - name: Deploy kube-prometheus-stack (Namespace observability)
      kubernetes.core.helm:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        name: prometheus-stack
        chart_ref: prometheus-community/kube-prometheus-stack
        release_namespace: observability
        create_namespace: true
        values:
          grafana:
            spec:
              strategy:
                type: Recreate # Em vez de RollingUpdate
            service:
              type: NodePort
              nodePort: 32000
            persistence:
              enabled: true
              type: pvc
              storageClassName: local-path # Storage padrão do K3s
              accessModes:
                - ReadWriteOnce
              size: 5Gi  
            # --- CONFIGURAÇÃO AUTOMÁTICA DE DATA SOURCES ---
            additionalDataSources:
              - name: Loki
                type: loki
                url: http://172.22.0.29:3100 # Seu IP externo do Loki
                jsonData:
                  derivedFields:
                    - datasourceUid: jaeger-datasource-id
                      matcherRegex: "traceID=(\\w+)"
                      name: TraceID
                      url: "$${__value.raw}" # O duplo $$ é para o Ansible não confundir com variável
              - name: Jaeger
                type: jaeger
                uid: jaeger-datasource-id
                url: http://jaeger-svc.observability:16686
                jsonData:
                  nodeGraph:
                    enabled: true  