name: "Proxmox IaC Pipeline"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: self-hosted
    environment: "Proxmox"
    
    # Colocar aqui no topo do job garante que todos os steps vejam as envs
    env:
      PM_API_URL: ${{ secrets.PROXMOX_API_URL }}
      PM_API_TOKEN_ID: ${{ secrets.PROXMOX_API_TOKEN_ID }}
      PM_API_TOKEN_SECRET: ${{ secrets.PROXMOX_API_TOKEN_SECRET }}
      TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug Secret Existence
        run: |
          echo "Verificando se os segredos existem (sem mostrar o conteúdo):"
          [ -n "${PM_API_URL}" ] && echo "URL: OK" || echo "URL: VAZIA"
          [ -n "${PM_API_TOKEN_ID}" ] && echo "TOKEN_ID: OK" || echo "TOKEN_ID: VAZIA"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
