name: "Proxmox IaC Pipeline"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: self-hosted
    environment: "Proxmox"
    
    defaults:
      run:
        working-directory: ./terraform


    # Variáveis de ambiente para todo o Job
    env:
      TF_VAR_ssh_public_key_ansible: ${{ secrets.SSH_PUBLIC_KEY_ANSIBLE }}
      TF_VAR_ssh_public_key_admin: ${{ secrets.SSH_PUBLIC_KEY_ADMIN }}
      TF_VAR_proxmox_api_url: ${{ secrets.PROXMOX_API_URL }}
      TF_VAR_proxmox_api_token_id: ${{ secrets.PROXMOX_API_TOKEN_ID }}
      TF_VAR_proxmox_api_token_secret: ${{ secrets.PROXMOX_API_TOKEN_SECRET }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug Secret Existence
        run: |
          echo "Verificando se os segredos chegaram ao Runner:"
          [ -n "${TF_VAR_proxmox_api_url}" ] && echo "URL: OK" || echo "URL: VAZIA"
          [ -n "${TF_VAR_proxmox_api_token_id}" ] && echo "TOKEN_ID: OK" || echo "TOKEN_ID: VAZIA"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve

      - name: Aguardar SSH (Porta 22) ficar disponível
        shell: bash  # Garante que estamos usando o Bash e não o Sh
        run: |
          echo "Aguardando as VMs responderem na porta 22..."
          for ip in 172.22.0.29 172.22.0.30 172.22.0.31; do
            echo "Checando $ip..."
            # Tenta abrir um socket TCP na porta 22. Se falhar, espera 5 segundos.
            until timeout 2 bash -c "echo > /dev/tcp/$ip/22" 2>/dev/null; do
              echo "Aguardando $ip (ainda não respondeu)..."
              sleep 5
            done
            echo "$ip está pronto!"
          done

      - name: Testar conexão com as VMs (Ansible Ping)
        if: github.ref == 'refs/heads/main'
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          # Usando o nome correto que definimos anteriormente
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_ANSIBLE }}
        run: |
          # Criar o arquivo da chave privada temporariamente
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Teste de Ping via Ansible (Master e Workers)
          ansible all -i "172.22.0.29,172.22.0.30,172.22.0.31," \
                  -m ping \
                  -u ubuntu \
                  --private-key private_key.pem

      - name: Executar Preparação de SRE (Ansible)
        if: github.ref == 'refs/heads/main'
        # Esta linha abaixo é o segredo: ela anula o default de ./terraform apenas para este passo
        working-directory: . 
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_ANSIBLE }}
        run: |
          # Agora o bash está na raiz do projeto
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          # O caminho "ansible/k8s-prep.yml" agora faz sentido para o Runner
          ansible-playbook -i "172.22.0.29,172.22.0.30,172.22.0.31," \
                           ansible/k8s-prep.yml \
                           -u ubuntu \
                           --private-key private_key.pem

      - name: Executar Instalação do K3s
        if: github.ref == 'refs/heads/main'
        working-directory: . # Força a raiz do repo
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_ANSIBLE }}
        run: |
          # DEBUG: Vamos ver onde estamos e o que tem aqui
          echo "Diretório atual: $(pwd)"
          ls -R ansible/
          
          # Comando original
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ansible-playbook -i ansible/inventory.ini \
                           ansible/k3s-install.yml \
                           --private-key private_key.pem

    # ... passos anteriores do Ansible (Prep e Install) ...

      - name: Executar Deploy do Promtail Native
        if: github.ref == 'refs/heads/main'
        working-directory: .
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_ANSIBLE }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          # Rodando o deploy da aplicação
          ansible-playbook -i ansible/inventory.ini \
                           ansible/deploy-promtail-native.yml \
                           --private-key private_key.pem

      - name: Criar namaspces pos install 
        if: github.ref == 'refs/heads/main'
        working-directory: .
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_ANSIBLE }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          ansible-playbook -i ansible/inventory.ini \
                           ansible/k8s-pos-install.yml \
                           --private-key private_key.pem        
                              
      - name: Instalar Jaeger Tracing 
        if: github.ref == 'refs/heads/main'
        working-directory: .
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_ANSIBLE }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          ansible-playbook -i ansible/inventory.ini \
                           ansible/k8s-jaeger-deploy.yml \
                           --private-key private_key.pem        
                   
      - name: Instalar Stack de Observabilidade (Prometheus/Grafana)
        if: github.ref == 'refs/heads/main'
        working-directory: .
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_ANSIBLE }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          ansible-playbook -i ansible/inventory.ini \
                           ansible/k8s-observability-stack.yml \
                           --private-key private_key.pem 

      - name: Executar Deploy do Banco da aplicação Web
        if: github.ref == 'refs/heads/main'
        working-directory: .
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_ANSIBLE }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
        
          ansible-playbook -i ansible/inventory.ini \
                           ansible/k8s-web-db-deploy.yml \
                           --private-key private_key.pem

      - name: Executar Deploy do backend da aplicação Web
        if: github.ref == 'refs/heads/main'
        working-directory: .
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_ANSIBLE }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
        
          ansible-playbook -i ansible/inventory.ini \
                           ansible/k8s-web-backend-deploy.yml \
                           --private-key private_key.pem

      - name: Executar Deploy do Frontend da aplicação Web
        if: github.ref == 'refs/heads/main'
        working-directory: .
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_ANSIBLE }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
        
          ansible-playbook -i ansible/inventory.ini \
                           ansible/k8s-web-frontend-deploy.yml \
                           --private-key private_key.pem

      - name: 🛡️ Health Check de Infraestrutura e Apps
        if: github.ref == 'refs/heads/main'
        working-directory: .
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_ANSIBLE }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          echo "--- 1. Checando Serviços Systemd ---"
          # Master roda k3s
          ansible k8s_master -i ansible/inventory.ini -u ubuntu --private-key private_key.pem \
                  -m shell -a "systemctl is-active k3s"
          # Workers rodam k3s-agent
          ansible k8s_workers -i ansible/inventory.ini -u ubuntu --private-key private_key.pem \
                  -m shell -a "systemctl is-active k3s-agent"
          # Ambos rodam promtail
          ansible all -i ansible/inventory.ini -u ubuntu --private-key private_key.pem \
                  -m shell -a "systemctl is-active promtail"

          echo "--- 2. Status Pods (Observability) ---"
          ansible k8s_master -i ansible/inventory.ini -u ubuntu --private-key private_key.pem \
                  -m shell -a "sudo kubectl get pods -n observability"

          echo "--- 3. Status Pods (Shop-Lab) ---"
          ansible k8s_master -i ansible/inventory.ini -u ubuntu --private-key private_key.pem \
                  -m shell -a "sudo kubectl get pods -n shop-lab"                  

          echo "--- 4. Testando Acessibilidade ---"
          # Adicionado retry para aguardar o pod subir 100%
          for i in {1..10}; do 
            CODE=$(curl -s -o /dev/null -w "%{http_code}" --connect-timeout 5 http://172.22.0.29:30500)
            if [ "$CODE" == "200" ]; then echo "Sucesso: 200"; exit 0; fi
            echo "Tentativa $i: Status $CODE... aguardando."
            sleep 5
          done
          exit 1